# Copyright 2022 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: warn
site:
  title: Enterprise Contract
  url: https://enterprisecontract.dev/docs
  start_page: user-guide::index.adoc
  robots: allow
content:
  sources:
    - url: https://github.com/enterprise-contract/ec-policies.git
      start_path: antora/docs

    - url: https://github.com/enterprise-contract/ec-cli.git
      start_path: docs

    - url: https://github.com/enterprise-contract/enterprise-contract-controller.git
      start_path: docs

    - url: https://github.com/enterprise-contract/user-guide.git

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ../website/antora/docs
antora:
  extensions:
    - '@antora/lunr-extension'
    - require: './extensions/zoom.js'
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
