baseURL = 'https://enterprise-contract.dev/'
languageCode = 'en-us'
title = 'Enterprise Contract'
theme = 'antora-default-ui-hugo-theme'
publishDir = '../public'
copyright = "Red Hat, Inc. All rights reserved."

[params]
  since = 2023

[markup]
  [markup.asciidocext]
    [markup.asciidocext.attributes]
      "icons" = "font"
      "source-highlighter" = "highlightjs"
  [markup.highlight]
    # Disable Goldmark Chroma syntax highlighter
    codeFences = false

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  #[[menu.main]]
  #  name = 'About'
  #  pageRef = '/about'
  #  weight = 20

  [[menu.main]]
    name = 'Documentation'
    url = '/docs'
    weight = 30
