baseURL = 'https://enterprise-contract.dev/'
languageCode = 'en-us'
title = 'Enterprise Contract'
theme = 'github.com/basil/antora-default-ui-hugo-theme'
publishDir = '../public'
copyright = "Red Hat, Inc. All rights reserved."
relativeURLs = true

[params]
  since = 2023

[markup]
  [markup.asciidocext]
    [markup.asciidocext.attributes]
      "icons" = "font"
      "source-highlighter" = "highlightjs"
  [markup.highlight]
    # Disable Goldmark Chroma syntax highlighter
    codeFences = false

[menu]
  #
  # See also antora/supplemental-ui/partials/header-content.hbs
  # The links there should be kept in sync with these links.
  # TODO: DRY it up and generate the menus from a single source.
  #
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menu.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 11

  [[menu.main]]
    name = 'Source Code'
    url = 'https://github.com/enterprise-contract'
    weight = 50

  #[[menu.main]]
  #  name = 'About'
  #  pageRef = '/about'
  #  weight = 20

  [[menu.main]]
    name = 'Documentation'
    weight = 30

  [[menu.main]]
    parent = 'Documentation'
    name = 'Overview'
    url = '/docs/ec/main'
    weight = 10

  [[menu.main]]
    parent = 'Documentation'
    name = 'CLI Reference'
    url = '/docs/ec-cli/main/ec_validate_image.html'
    weight = 20

  [[menu.main]]
    parent = 'Documentation'
    name = 'Tekton Tasks'
    url = '/docs/ec-cli/main/verify-enterprise-contract.html'
    weight = 30

  [[menu.main]]
    parent = 'Documentation'
    name = 'Configuration'
    url = '/docs/ecc/main'
    weight = 40

  [[menu.main]]
    parent = 'Documentation'
    name = 'Policies'
    url = '/docs/ec-policies/release_policy.html'
    weight = 60

  [[menu.main]]
    parent = 'Documentation'
    name = 'User Guide'
    url = '/docs/user-guide/main'
    weight = 70

[module]
[[module.imports]]
  path = 'github.com/basil/antora-default-ui-hugo-theme'
